Allow-user-written-suggestion
gla6-fp-team1/gaelic-project pull request #35
Opened 2023-10-10 21:25 UTC by Melesegithub

UX/Allow user-written suggestion. I have just recorded the original sentence id and user-provided-correction on user_interaction table.

2023-10-11 00:42 UTC, sztupy commented on client/src/pages/UserSuggestion.js
> +        console.log(formData);
make sure to remove logging from published PRs

2023-10-11 00:43 UTC, sztupy commented on client/src/pages/UserSuggestion.js
> +			<div>
indentation is off in this section, please clean it up

2023-10-11 00:45 UTC, sztupy commented on server/api.js
> +router.post("/save-correction", async (req, res) => {
why the need to have this as a separate endpoint? Can't the `/save-suggestions` endpoint be updated to allow suggestions? We could then still save the shown suggestions to the database as well, which could be useful for researchers to know what options were not taken.

2023-10-11 08:48 UTC, Melesegithub commented on server/api.js
> +router.post("/save-correction", async (req, res) => {
I will try to fix that thanks

2023-10-12 00:03 UTC, sztupy commented on server/api.js
> +router.post("/save-correction", async (req, res) => {
This is still an effective duplication of the `/save-suggestion` endpoint above. You can definitely design the `/save-suggestion` endpoint to support all four use cases:

- Original sentence was correct
- One of the suggestions have been picked
- None of the suggestions are correct button was used
- A typed in suggestion was used

2023-10-12 00:04 UTC, sztupy requested changes
Solution should use a single endpoint for all relevant functionality

2023-10-14 12:46 UTC, closed without merging