#38 - Query performance and Database setup script - Appolin Semegni Fotso
gla6-fp-team1/gaelic-project pull request #54
Opened 2023-10-18 12:13 UTC by AppolinFotso

## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description

I updated the getRandomIndex function in api.js file so that zero will not be generated as a random number. I changed how the database is queried for a random sentence by counting the number of cells with no null value in the count column.  and then passing that to the getRandomIndex function which generate a specific number which is further used to retrieve a single sentence from the database.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #38

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

2023-10-18 13:48 UTC, sztupy requested changes

2023-10-18 13:48 UTC, sztupy commented on server/db-schema.sql
> +  selected_suggestion INTEGER,
This change needs the relevant change in the codebase, currently the system will try to save the textual value, which will be converted to `0`

2023-10-18 13:49 UTC, sztupy commented
Rest of the changes look okay for now!

2023-10-18 15:11 UTC, AppolinFotso commented on server/db-schema.sql
> +  selected_suggestion INTEGER,
I changed the codebase to reflect the schema. Please let me know if I have taken the right approach.

2023-10-19 10:08 UTC, sztupy commented on server/api.js
> +	res.json([randomSentence, randomSentenceId]);
Prefer returning objects:

```
{
  sentence: <sentence>,
  id: <id>
}
```

2023-10-19 10:10 UTC, sztupy commented on client/src/pages/Home.js
> +								randomTextId={randomTextId}
while this will send the ID over to the SubmitSuggestion component, it still sends the sentence back. It should actually send both data back to the API

2023-10-19 10:11 UTC, sztupy commented on server/db-schema.sql
> +  selected_suggestion INTEGER,
Yes, this looks good, Going to verify it locally

2023-10-19 10:19 UTC, sztupy requested changes
There is a bug when using the "none of the suggestions are useful" and the "original sentence is correct" buttons - the sentence ID is not stored in the database:

```
cyf=# select * from user_interactions;
 id | sentence_id | selected_suggestion | user_provided_suggestion | original_sentence_was_correct
----+-------------+---------------------+--------------------------+-------------------------------
  1 |           5 |                   1 |                          |
  2 |           4 |                   5 |                          |
  3 |           5 |                   9 |                          |
  4 |             |                     |                          | t
  5 |             |                     | own correction           |
(5 rows)
```

As you can se rows 4 & 5 are missing the `sentenceId` values.

Rest of the code looks to be working and is what is expected!

2023-10-19 10:20 UTC, sztupy commented
Do note I have merged in main, so when you continuw orking make sure to pull this branch first

2023-10-19 10:36 UTC, AppolinFotso commented
I did not check those two buttons because they were not part of the ticket and I thought someone else was working on them.
I am at work at the moment but I will check them when I get home this evening. Thanks

2023-10-19 10:46 UTC, sztupy commented
Hi, the ticket didn't mention them as they didn't exist yet. They were added since, and functionality wise they should remain working for any feature we merge afterwards - otherwise we cause a regression and a loss of feature.

Note: if you need to redesign their UX to be more in line with how the other buttons work that won't be a problem (specifically the "Correct" button looks a bit too convoluted)

2023-10-19 20:01 UTC, AppolinFotso commented
The sentence ID is now stored in the **user_interactions** table when either of the two buttons is clicked.

2023-10-19 22:29 UTC, sztupy commented
Couple minor issues, but I'll address them later, the code looks to be working now and does what is expected

2023-10-19 22:29 UTC, sztupy approved these changes

2023-10-19 22:29 UTC, merged